services: 
  dev-db: 
    image: postgres:13
    ports: 
      - 5444:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    networks:
      - mgrc

networks:
  mgrc: 